spring:
  datasource:
    url: jdbc:h2:mem:testdb

    username: test
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    Driver:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
