spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/newdb
    username: root
    password: Aa0112358)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  jackson:
    serialization:
      fail-on-empty-beans: false